### ISSUE TITLE
Doc2vec和Bert模型

### ISSUE THREAD

**Issue by pojiuk** [SirryChen/CACL#1]
您好！我对您的这篇文章很感兴趣，看您的代码中使用到了Doc2vec和Bert，请问方便分享一下训练好的模型吗？非常感谢~

**Comment by SirryChen** [comment]
非常感谢您对我们工作的关注。

- 我们主要使用wiki百科和twitter上的语料训练[Doc2vec](https://radimrehurek.com/gensim/auto_examples/tutorials/run_doc2vec_lee.html)模型，稍后会更新训练模型的代码至仓库，方便您根据需要训练自定义输出维度的模型。
- Bert则是直接使用了[bert-base-uncased](https://huggingface.co/google-bert/bert-base-uncased)权重，没有进行微调，您可以直接使用hugging face中提供的transformers接口进行加载并使用。
